/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Common.Utilidades;
import Common.factura;
import Common.proveedorcomponente;
import Dominio.dEmpresa;
import com.toedter.calendar.JDateChooser;
import datechooser.beans.DateChooserCombo;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Faishi
 */
public class Listados extends javax.swing.JFrame {
   private int Total;
   private ArrayList<factura> ListaFacturas = new ArrayList<factura>();
   private ArrayList<proveedorcomponente> ListaProveedoresComponentes = new ArrayList<proveedorcomponente>();
   /**
     * Creates new form Listados
     */
   private dEmpresa dEmpresa;
    public Listados(dEmpresa pEmp) {
        initComponents();
         dEmpresa = pEmp;
    }
    
    public Listados() {
        initComponents();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllst2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllstdate = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fecha1 = new com.toedter.calendar.JDateChooser();
        fecha2 = new com.toedter.calendar.JDateChooser();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Listado de componentes por debajo de la cantidad mínima en stock con la lista de proveedores posibles para cada uno.");

        tbllst2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Componente", "Cantidad Componente", "Id Proveedor", "Nombre Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbllst2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tbllst2HierarchyChanged(evt);
            }
        });
        tbllst2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbllst2FocusGained(evt);
            }
        });
        tbllst2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllst2MouseClicked(evt);
            }
        });
        tbllst2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbllst2CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tbllst2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbllst2PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tbllst2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado 1", jPanel1);

        tbllstdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Factura", "Id Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbllstdate.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tbllstdateHierarchyChanged(evt);
            }
        });
        tbllstdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbllstdateFocusGained(evt);
            }
        });
        tbllstdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllstdateMouseClicked(evt);
            }
        });
        tbllstdate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbllstdateCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tbllstdate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbllstdatePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbllstdate);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Total Facturado para un período dado.");

        jLabel3.setText("Facturado Desde:");

        jLabel4.setText("Facturado Hasta:");

        btnListar.setText("Listar");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Total Facturado hasta la Fecha:");

        txtTotal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnListar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado 2", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbllstdatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbllstdatePropertyChange

    }//GEN-LAST:event_tbllstdatePropertyChange

    private void tbllstdateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbllstdateCaretPositionChanged

    }//GEN-LAST:event_tbllstdateCaretPositionChanged

    private void tbllstdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllstdateMouseClicked
       
    }//GEN-LAST:event_tbllstdateMouseClicked

    private void tbllstdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbllstdateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllstdateFocusGained

    private void tbllstdateHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tbllstdateHierarchyChanged

    }//GEN-LAST:event_tbllstdateHierarchyChanged

    private void tbllst2HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tbllst2HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllst2HierarchyChanged

    private void tbllst2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbllst2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllst2FocusGained

    private void tbllst2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllst2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllst2MouseClicked

    private void tbllst2CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbllst2CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllst2CaretPositionChanged

    private void tbllst2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbllst2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllst2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listados().setVisible(true);
            }
        });
    }
    
    private void ReiniciarControles() {
       
        this.LimpiarList();
        this.CargarDatosList();
    }

    public void LimpiarList() {
        DefaultTableModel dm = (DefaultTableModel) this.tbllstdate.getModel();
        dm.setRowCount(0);
        this.tbllstdate.setModel(dm);//limpia el jtable
    }

   
    
    public void CargarDatosList() {
        ArrayList<proveedorcomponente> coleccion = new ArrayList<proveedorcomponente>();
        try {
            coleccion = dEmpresa.buscarTodosProveedoresComponentes();
            ListaProveedoresComponentes = coleccion;
            Iterator<proveedorcomponente> it = coleccion.iterator();
            while (it.hasNext()) {
            proveedorcomponente unProveedorComponente = it.next(); 
            if(unProveedorComponente.getIdComponenteProveedorComponente().getCantStockComp() < unProveedorComponente.getIdComponenteProveedorComponente().getCantMinStockComp()){
               // if(unComponente.getCantStockComp() < unComponente.getCantMinStockComp()){

                DefaultTableModel tm = (DefaultTableModel) tbllst2.getModel();
                tm.addRow(new Object[]{new Integer(unProveedorComponente.getIdComponenteProveedorComponente().getIdComp()),
                    new Integer(unProveedorComponente.getIdComponenteProveedorComponente().getCantStockComp()),
                    new Integer(unProveedorComponente.getIdProveedorProveedorComponente().getIdProveedor()),
                    new String(unProveedorComponente.getIdProveedorProveedorComponente().getNombreProveedor())});
                 
                tbllst2.setModel(tm);}
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Componente", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt){                                           
       ArrayList<factura> coleccion = new ArrayList<factura>();
        try {
            coleccion = dEmpresa.buscarTodosFacturas();
            ListaFacturas = coleccion;
            Iterator<factura> it = coleccion.iterator();
            while (it.hasNext()) {
            factura unFactura = it.next(); 
            String FechaI = Utilidades.convertirDateUtilAString(this.fecha1.getDate());
            String FechaF = Utilidades.convertirDateUtilAString(this.fecha2.getDate());
            String FechaC = Utilidades.convertirDateUtilAString(unFactura.getFechaPagoFactura());
            if(FechaC.compareTo(FechaI) > 0 && 
                    FechaC.compareTo(FechaF) < 0){ 
                Total++;
                DefaultTableModel tm = (DefaultTableModel) tbllst2.getModel();
                tm.addRow(new Object[]{new Integer(unFactura.getIdFactura()),
                    new String(Utilidades.convertirDateUtilAString(unFactura.getFechaPagoFactura()))});
                 
                tbllst2.setModel(tm);
            }
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Componente", JOptionPane.ERROR_MESSAGE);
        }
        String Totall = String.valueOf(Total);
        this.txtTotal.setText(Totall);
        
    }       
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private com.toedter.calendar.JDateChooser fecha1;
    private com.toedter.calendar.JDateChooser fecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbllst2;
    private javax.swing.JTable tbllstdate;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
