/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Common.Utilidades;
import Common.cDatosException;
import Common.cliente;
import Common.motores;
import Common.pedido;
import Dominio.dEmpresa;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class vPedido extends javax.swing.JFrame {

    private ArrayList<pedido> ListaPedidos = new ArrayList<pedido>();

    /**
     * Creates new form vPedido
     */
    public vPedido() {
        initComponents();
    }
    private dEmpresa dEmpresa;

    public vPedido(dEmpresa pEmp) {
        initComponents();
        dEmpresa = pEmp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdcFchPed = new com.toedter.calendar.JDateChooser();
        jcbCliPed = new javax.swing.JComboBox<>();
        jcbMotPed = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPed = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdPed1 = new javax.swing.JTextField();
        jdcFchPed1 = new com.toedter.calendar.JDateChooser();
        txtCliPed1 = new javax.swing.JTextField();
        txtMotPed1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Fecha entrega:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel5.setText("Motor:");

        jLabel9.setText("Cliente:");

        jcbCliPed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCliPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCliPedActionPerformed(evt);
            }
        });

        jcbMotPed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcFchPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCliPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMotPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 377, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbCliPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jdcFchPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcbMotPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnAgregar)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        tblPed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Fecha entrega", "Motor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPed.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblPedHierarchyChanged(evt);
            }
        });
        tblPed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblPedFocusGained(evt);
            }
        });
        tblPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedMouseClicked(evt);
            }
        });
        tblPed.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblPedCaretPositionChanged(evt);
            }
        });
        tblPed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblPedPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblPed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel10.setText("Cliente:");

        jLabel8.setText("Fecha entrega:");

        jLabel11.setText("Motor:");

        jLabel13.setText("Id:");

        txtIdPed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPed1ActionPerformed(evt);
            }
        });

        txtCliPed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCliPed1ActionPerformed(evt);
            }
        });

        txtMotPed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotPed1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPed1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jdcFchPed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCliPed1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMotPed1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtIdPed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCliPed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jdcFchPed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMotPed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar/Eliminar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPedHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblPedHierarchyChanged

    }//GEN-LAST:event_tblPedHierarchyChanged

    private void tblPedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblPedFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPedFocusGained

    private void tblPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedMouseClicked
        int fila = this.tblPed.getSelectedRow();

        if (fila >= 0) {
            DefaultTableModel tm = (DefaultTableModel) this.tblPed.getModel();
            int numFilas = tm.getRowCount();
            if ((fila < numFilas) && (fila >= 0)) {

                // tomo los datos de los componentes existentes
                String id = String.valueOf(tm.getValueAt(fila, 0));
                String cli = String.valueOf(tm.getValueAt(fila, 1));
                Date fecha;
                try {
                    fecha = (Date) Utilidades.convertirDeStringAUtilDate(String.valueOf(tm.getValueAt(fila, 2)));
                    this.jdcFchPed1.setDate(fecha);
                } catch (ParseException ex) {
                    Logger.getLogger(vPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
                String mot = String.valueOf(tm.getValueAt(fila, 3));

                this.txtIdPed1.setText(id);
                
                this.txtCliPed1.setText(cli);
                this.txtMotPed1.setText(mot);

            }
        }
    }//GEN-LAST:event_tblPedMouseClicked

    private void tblPedCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblPedCaretPositionChanged

    }//GEN-LAST:event_tblPedCaretPositionChanged

    private void tblPedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblPedPropertyChange

    }//GEN-LAST:event_tblPedPropertyChange

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        pedido unPedido = new pedido();
        int num;
        try {
            if (!this.txtIdPed1.getText().equals("")) {
                num = Integer.parseInt(this.txtIdPed1.getText());
                unPedido.setIdPedido(num);
                dEmpresa.eliminarPedido(unPedido);
                JOptionPane.showMessageDialog(this, "Se dado eliminado correctamente", "Componente", JOptionPane.INFORMATION_MESSAGE);
                ReiniciarControles();
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un registro", "Componente", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Componente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (!this.txtIdPed1.getText().equals("") && !this.txtCliPed1.getText().equals("") && !this.txtMotPed1.getText().equals("")) {
            cliente unCliente = new cliente();
            motores unMotor = new motores();
            try {

                Integer num;
                Integer cli;
                Integer mot;
                Date fech;
                pedido unPedido = new pedido();
                num = Integer.parseInt(this.txtIdPed1.getText());
                cli = Integer.parseInt(this.txtCliPed1.getText());
                mot = Integer.parseInt(this.txtMotPed1.getText());
                fech = this.jdcFchPed1.getDate();

                unPedido.setIdPedido(num);
                unPedido.setFechaDeEntregaPedido(fech);
                unCliente.setIdClie(cli);
                unPedido.setIdClientePedido(dEmpresa.buscarCliente(unCliente));
                unMotor.setIdMotor(mot);
                unPedido.setIdMotorPedido(dEmpresa.buscarMotor(unMotor));
                dEmpresa.modificarPedido(unPedido);
                ReiniciarControles();
                JOptionPane.showMessageDialog(this, "Se ha modificado correctamente", "Tipo", JOptionPane.INFORMATION_MESSAGE);

            } catch (cDatosException e) {
                JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Datos ingresados incorrectamente", "Accion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtIdPed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPed1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        pedido unPedido;
        cliente unCliente;
        motores unMotor;

        try {
            unPedido = new pedido();
            unCliente = new cliente();
            unMotor = new motores();

            unCliente = (cliente) this.jcbCliPed.getSelectedItem();
            unMotor = (motores) this.jcbMotPed.getSelectedItem();

            unPedido.setIdClientePedido(unCliente);
            unPedido.setIdMotorPedido(unMotor);
            unPedido.setFechaDeEntregaPedido(this.jdcFchPed.getDate());

            dEmpresa.agregarPedido(unPedido);
            JOptionPane.showMessageDialog(this, "Se dado de alta correctamente", "Pedido", JOptionPane.INFORMATION_MESSAGE);

            ReiniciarControles();

        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtCliPed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliPed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliPed1ActionPerformed

    private void txtMotPed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotPed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotPed1ActionPerformed

    private void jcbCliPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCliPedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCliPedActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       this.txtIdPed1.setEditable(false);
        this.ReiniciarControles();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPedido().setVisible(true);
            }
        });
    }

    private void ReiniciarControles() {
        this.LimpiarCampos();
        this.LimpiarList();
        this.CargarDatosList();
        this.CargarComboCliente();
        this.CargarComboMotor();
    }

    public void LimpiarList() {
        DefaultTableModel dm = (DefaultTableModel) this.tblPed.getModel();
        dm.setRowCount(0);
        this.tblPed.setModel(dm);//limpia el jtable
    }

    public void CargarDatosList() {
        ArrayList<pedido> coleccion = new ArrayList<pedido>();
        try {
            coleccion = dEmpresa.buscarTodosPedidosSinEliminados();
            ListaPedidos = coleccion;

            Iterator<pedido> it = coleccion.iterator();
            while (it.hasNext()) {
                pedido unPedido = it.next();
                DefaultTableModel tm = (DefaultTableModel) tblPed.getModel();
                tm.addRow(new Object[]{new Integer(unPedido.getIdPedido()),
                    new Integer(unPedido.getIdClientePedido().getIdClie()),
                    new String(Utilidades.convertirDateUtilAString(unPedido.getFechaDeEntregaPedido())),
                    new Integer(unPedido.getIdMotorPedido().getIdMotor())});
                tblPed.setModel(tm);
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void LimpiarCampos() {
        this.txtIdPed1.setText("");
        this.txtCliPed1.setText("");
        this.txtMotPed1.setText("");

    }

    public void CargarComboCliente() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        jcbCliPed.setModel(modelo);
        this.jcbCliPed.removeAllItems();
        ArrayList<cliente> coleccion = new ArrayList<cliente>();
        try {
            coleccion = dEmpresa.buscarTodosClientesSinEliminados();
            for (cliente cli : coleccion) {
                modelo.addElement(cli);
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Cliente", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void CargarComboMotor() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        jcbMotPed.setModel(modelo);
        this.jcbMotPed.removeAllItems();
        ArrayList<motores> coleccion = new ArrayList<motores>();
        try {
            coleccion = dEmpresa.buscarTodosMotoresSinEliminados();
            for (motores mot : coleccion) {
                modelo.addElement(mot);
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Motor", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbCliPed;
    private javax.swing.JComboBox<String> jcbMotPed;
    private com.toedter.calendar.JDateChooser jdcFchPed;
    private com.toedter.calendar.JDateChooser jdcFchPed1;
    private javax.swing.JTable tblPed;
    private javax.swing.JTextField txtCliPed1;
    private javax.swing.JTextField txtIdPed1;
    private javax.swing.JTextField txtMotPed1;
    // End of variables declaration//GEN-END:variables
}
